// ─── Canonical 14 Meetings for Studenckie Koło Naukowe Seksuologii WSKZ (2025/2026) ─

export const CANONICAL_MEETINGS_2025_2026 = [
  {
    id: 'M01',
    code: 'M01',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2025-12-15',
    dateFormatted: '15.12.2025',
    type: 'Journal Club',
    title: 'Współczesne kierunki badań nad seksualnością człowieka i wprowadzenie do Journal Club',
    speaker: 'Tomasz Bratkowski, mgr Ewa Skupińska',
    attendeesCount: 74,
    location: 'Online (MS Teams)',
    isMandatory: true,
  },
  {
    id: 'M02',
    code: 'M02',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-01-12',
    dateFormatted: '12.01.2026',
    type: 'Journal Club / Seminarium',
    title: 'Modele tożsamości psychoseksualnej i dysforii płciowej w ujęciu ICD-11',
    speaker: 'Ewelina Kozłowska',
    attendeesCount: 68,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M03',
    code: 'M03',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-01-26',
    dateFormatted: '26.01.2026',
    type: 'Wykład Merytoryczny',
    title: 'Zaburzenia pożądania i podniecenia seksualnego – podejście biopsychospołeczne',
    speaker: 'Tomasz Bratkowski',
    attendeesCount: 72,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M04',
    code: 'M04',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-02-02',
    dateFormatted: '02.02.2026',
    type: 'Warsztat Kliniczny',
    title: 'Metodologia wywiadu seksuologicznego w praktyce diagnostycznej psychologa',
    speaker: 'Tomasz Bratkowski, Ewelina Kozłowska',
    attendeesCount: 65,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M05',
    code: 'M05',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-02-16',
    dateFormatted: '16.02.2026',
    type: 'Journal Club',
    title: 'Trauma wczesnodziecięca i mechanizmy obronne w ujęciu psychoseksuologicznym',
    speaker: 'Nomin Galindev, Tomasz Bratkowski',
    attendeesCount: 70,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M06',
    code: 'M06',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-03-02',
    dateFormatted: '02.03.2026',
    type: 'Seminarium Kliniczne',
    title: 'Parafilie i zaburzenia preferencji seksualnych – diagnoza kliniczna i opiniodawstwo sądowe',
    speaker: 'mgr Martyna Dziekan, Tomasz Bratkowski',
    attendeesCount: 63,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M07',
    code: 'M07',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-03-16',
    dateFormatted: '16.03.2026',
    type: 'Prezentacje Studenckie',
    title: 'Komunikacja intymna, asertywność seksualna i satysfakcja w związkach partnerskich',
    speaker: 'Paula Kamzol, Dorota Rogulska',
    attendeesCount: 66,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M08',
    code: 'M08',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-04-13',
    dateFormatted: '13.04.2026',
    type: 'Journal Club',
    title: 'Wpływ gospodarki hormonalnej i farmakoterapii na funkcje seksualne oraz nastrój',
    speaker: 'Tomasz Bratkowski, Ewelina Kozłowska',
    attendeesCount: 69,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M09',
    code: 'M09',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-04-27',
    dateFormatted: '27.04.2026',
    type: 'Warsztat Metodologiczny',
    title: 'Projektowanie badań empirycznych i analiza danych statystycznych w seksuologii',
    speaker: 'mgr Ewa Skupińska',
    attendeesCount: 58,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M10',
    code: 'M10',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-05-11',
    dateFormatted: '11.05.2026',
    type: 'Seminarium Badawcze',
    title: 'Prezentacja wstępnych wyników ogólnopolskiego badania ankietowego Koła Seksuologii',
    speaker: 'Tomasz Bratkowski, Ewelina Kozłowska',
    attendeesCount: 71,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M11',
    code: 'M11',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-05-25',
    dateFormatted: '25.05.2026',
    type: 'Journal Club',
    title: 'Ból seksualny (dyspareunia, wulwodynia) – diagnoza i terapia interdyscyplinarna',
    speaker: 'Agnieszka Rydz, Paula Kamzol',
    attendeesCount: 64,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M12',
    code: 'M12',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-06-08',
    dateFormatted: '08.06.2026',
    type: 'Podsumowujące / Sprawozdawcze',
    title: 'Roczne podsumowanie działalności naukowej Koła i ewaluacja projektów 2025/2026',
    speaker: 'Zarząd Koła, mgr Ewa Skupińska, mgr Martyna Dziekan',
    attendeesCount: 76,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M13',
    code: 'M13',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-06-22',
    dateFormatted: '22.06.2026',
    type: 'Konferencja Stacjonarna',
    title: 'Ogólnopolska Konferencja Seksuologiczna „Budowanie Mostów” – Prezentacje i Warsztaty',
    speaker: 'Ewelina Kozłowska, Tomasz Bratkowski',
    attendeesCount: 42,
    location: 'Kampus WSKZ / Hybrydowo',
    isMandatory: false,
  },
  {
    id: 'M14',
    code: 'M14',
    name: 'Studenckie Koło Naukowe Seksuologii WSKZ',
    date: '2026-07-06',
    dateFormatted: '06.07.2026',
    type: 'Warsztat Publikacyjny',
    title: 'Przygotowanie monografii naukowej i publikacji w czasopismach punktowanych MNiSW',
    speaker: 'Tomasz Bratkowski, mgr Ewa Skupińska',
    attendeesCount: 45,
    location: 'Online',
    isMandatory: false,
  },
];

/**
 * Filtruje techniczne wpisy organizacyjne (np. DEADLINE, przypomnienia, terminy zgłoszeń)
 */
export function filterLegitimateMeetings(meetings = [], orgId = 'skn-psychoonkologia') {
  if (!Array.isArray(meetings) || meetings.length === 0) return getCanonicalMeetingsForOrg(orgId || 'skn-psychoonkologia');

  const technicalKeywords = [
    'deadline',
    'termin',
    'weryfikacja',
    'przypomnienie',
    'ankieta',
    'zamknięcie',
    'odwołane',
    'techniczny',
    'testowe',
    'próba połączenia',
  ];

  const legitimate = meetings.filter(m => {
    const title = (m?.title || m?.name || '').toLowerCase();
    const type = (m?.type || '').toLowerCase();
    const isTech = technicalKeywords.some(kw => title.includes(kw) || type.includes(kw));
    return !isTech;
  });

  return legitimate.length > 0 ? legitimate : getCanonicalMeetingsForOrg(orgId || 'skn-psychoonkologia');
}

export const CANONICAL_MEETINGS_SKNU = [
  {
    id: 'M01',
    code: 'M01',
    name: 'SKN Psychologii Zachowań Ryzykownych i Uzależnień WSKZ',
    date: '2026-05-27',
    dateFormatted: '27.05.2026',
    type: 'Spotkanie organizacyjne',
    title: 'Spotkanie organizacyjne i wybór zarządu koła',
    speaker: 'Zarząd Koła / Założyciele',
    attendeesCount: 6,
    location: 'Online (MS Teams)',
    isMandatory: true,
  },
  {
    id: 'M02',
    code: 'M02',
    name: 'SKN Psychologii Zachowań Ryzykownych i Uzależnień WSKZ',
    date: '2026-06-08',
    dateFormatted: '08.06.2026',
    type: 'Wykład Merytoryczny',
    title: 'Wykład: Historia profilaktyki uzależnień',
    speaker: 'mgr Sławomir Pietrzak',
    attendeesCount: 19,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M03',
    code: 'M03',
    name: 'SKN Psychologii Zachowań Ryzykownych i Uzależnień WSKZ',
    date: '2026-06-25',
    dateFormatted: '25.06.2026',
    type: 'Seminarium / Dyskusja',
    title: 'II Spotkanie SKNU - "Luźne rozmowy"',
    speaker: 'dr Dorota Dyjakon, mgr Sławomir Pietrzak',
    attendeesCount: 62,
    location: 'Online',
    isMandatory: true,
  },
  {
    id: 'M04',
    code: 'M04',
    name: 'SKN Psychologii Zachowań Ryzykownych i Uzależnień WSKZ',
    date: '2026-07-16',
    dateFormatted: '16.07.2026',
    type: 'Warsztat Profilaktyczny',
    title: 'Warsztaty Programu "Unplugged"',
    speaker: 'Prowadzący warsztatów',
    attendeesCount: 8,
    location: 'Online',
    isMandatory: true,
  },
];

export const CANONICAL_MEETINGS_PSYCHOONKOLOGIA = [
  {
    id: '2089952664',
    code: '[26/27] M01',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-05-07',
    dateFormatted: '07.05.2026, 18:00',
    formattedDate: '07.05.2026, 18:00',
    start_dt: '2026-05-07T18:00:00+02:00',
    end_dt: '2026-05-07T19:30:00+02:00',
    type: 'Spotkanie organizacyjne',
    title: '🎗️🧪 Inauguracja Koła Naukowego Psychoonkologii | Zarząd Koła',
    who: 'mgr Paweł Pilkiewicz, Zarząd Koła',
    speaker: 'mgr Paweł Pilkiewicz, Zarząd Koła',
    attendeesCount: 41,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: true,
    isLive: true,
    isUpcoming: false,
    notes: 'Porządek spotkania: Wyznaczenie kierunków i przyszłych projektów koła, proces zapisów, wybory zarządu.',
  },
  {
    id: '2098131141',
    code: '[26/27] M02',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-05-21',
    dateFormatted: '21.05.2026, 18:00',
    formattedDate: '21.05.2026, 18:00',
    start_dt: '2026-05-21T18:00:00+02:00',
    end_dt: '2026-05-21T21:00:00+02:00',
    type: 'Warsztat',
    title: '📊🎗️ Warsztat: „Rozpoznawanie indywidualnych potrzeb i predyspozycji komunikacyjnych (Cztery Soczewki)” | Michał Sieradzan-Przybyłowicz',
    who: 'Michał Sieradzan-Przybyłowicz',
    speaker: 'Michał Sieradzan-Przybyłowicz',
    attendeesCount: 35,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: false,
    isLive: true,
    isUpcoming: false,
    notes: 'Diagnoza typu temperamentu wg testu "Cztery Soczewki" (prof. G. Nelson) oraz techniki pracy z różnymi typami osobowości.',
  },
  {
    id: '2093151269-rid-1779984000',
    code: '[26/27] M03',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-05-28',
    dateFormatted: '28.05.2026, 18:00',
    formattedDate: '28.05.2026, 18:00',
    start_dt: '2026-05-28T18:00:00+02:00',
    end_dt: '2026-05-28T20:00:00+02:00',
    type: 'Warsztat',
    title: '👨‍🏫 📊WARSZTATY - Kurs z psychoonkologii z mgr Pawłem Pilkiewiczem',
    who: 'mgr Paweł Pilkiewicz',
    speaker: 'mgr Paweł Pilkiewicz',
    attendeesCount: 38,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: true,
    isLive: true,
    isUpcoming: false,
    notes: 'Warsztaty z zakresu psychoonkologii - tematy kliniczne i praktyczne zastosowania wiedzy psychologicznej.',
  },
  {
    id: '2093578855-rid-1781193600',
    code: '[26/27] M04',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-06-11',
    dateFormatted: '11.06.2026, 18:00',
    formattedDate: '11.06.2026, 18:00',
    start_dt: '2026-06-11T18:00:00+02:00',
    end_dt: '2026-06-11T20:00:00+02:00',
    type: 'Warsztat',
    title: '👨‍🏫 📊WARSZTATY - Kurs z psychoonkologii z mgr Pawłem Pilkiewiczem',
    who: 'mgr Paweł Pilkiewicz',
    speaker: 'mgr Paweł Pilkiewicz',
    attendeesCount: 32,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: true,
    isLive: true,
    isUpcoming: false,
    notes: 'Warsztaty z zakresu psychoonkologii - część 2.',
  },
  {
    id: '2114714561',
    code: '[26/27] M05',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-06-16',
    dateFormatted: '16.06.2026, 18:00',
    formattedDate: '16.06.2026, 18:00',
    start_dt: '2026-06-16T18:00:00+02:00',
    end_dt: '2026-06-16T19:30:00+02:00',
    type: 'Wykład Merytoryczny',
    title: '🏥🎗️ Rola psychoonkologa w zespole terapeutycznym | Joanna Głowacka',
    who: 'Joanna Głowacka',
    speaker: 'Joanna Głowacka',
    attendeesCount: 45,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: true,
    isLive: true,
    isUpcoming: false,
    notes: 'Praca psychoonkologa w zespole medycznym, granice kompetencji, mapa drogowa wsparcia.',
  },
  {
    id: '2093578855-rid-1781798400',
    code: '[26/27] M06',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-06-18',
    dateFormatted: '18.06.2026, 18:00',
    formattedDate: '18.06.2026, 18:00',
    start_dt: '2026-06-18T18:00:00+02:00',
    end_dt: '2026-06-18T20:00:00+02:00',
    type: 'Warsztat',
    title: '👨‍🏫 📊WARSZTATY - Kurs z psychoonkologii z mgr Pawłem Pilkiewiczem',
    who: 'mgr Paweł Pilkiewicz',
    speaker: 'mgr Paweł Pilkiewicz',
    attendeesCount: 36,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: true,
    isLive: true,
    isUpcoming: false,
    notes: 'Warsztaty z zakresu psychoonkologii - część 3.',
  },
  {
    id: '2093578855-rid-1782403200',
    code: '[26/27] M07',
    name: 'Studenckie Koło Naukowe Psychoonkologii WSKZ',
    date: '2026-06-25',
    dateFormatted: '25.06.2026, 18:00',
    formattedDate: '25.06.2026, 18:00',
    start_dt: '2026-06-25T18:00:00+02:00',
    end_dt: '2026-06-25T20:00:00+02:00',
    type: 'Warsztat',
    title: '👨‍🏫 📊WARSZTATY - Kurs z psychoonkologii z mgr Pawłem Pilkiewiczem',
    who: 'mgr Paweł Pilkiewicz',
    speaker: 'mgr Paweł Pilkiewicz',
    attendeesCount: 40,
    attendees: [],
    location: 'Online (Google Meet)',
    isMandatory: true,
    isLive: true,
    isUpcoming: false,
    notes: 'Warsztaty z zakresu psychoonkologii - część 4 (Podsumowanie cyklu).',
  },
];

export function getCanonicalMeetingsForOrg(orgId = 'skn-psychoonkologia') {
  const cleanId = String(orgId || '').trim().toLowerCase();
  if (cleanId === 'skn-psychoonkologia' || cleanId === 'skn_psychoonkologia') {
    return CANONICAL_MEETINGS_PSYCHOONKOLOGIA;
  }
  if (cleanId === 'sknu') {
    return CANONICAL_MEETINGS_SKNU;
  }
  if (cleanId === 'skn_seksuologii') {
    return CANONICAL_MEETINGS_2025_2026;
  }
  return CANONICAL_MEETINGS_PSYCHOONKOLOGIA;
}

export function getCanonicalMeetings() {
  return CANONICAL_MEETINGS_PSYCHOONKOLOGIA;
}

export default CANONICAL_MEETINGS_PSYCHOONKOLOGIA;
